### ISSUE TITLE
Please fix the azure-pipeline.yaml

### ISSUE THREAD

**Issue by jesus-eec** [mikepfeiffer/node-express-azure#25]
Hi, Mike. Thank you for this app and DevOps Courses both CloudSkills and INE.

FYI... The **azure-pipeline.yaml** file has an Ubuntu 16.04 . When I run it into Azure DevOps CI, the job stop, indicating that the image is not available. I look into the current ubuntu images in Azure DevOps for CI Jobs and the only two images available are 18.04 and 20.04. I imagine this change could improve the .yaml file and be usefull for the INE labs and DevOps Foundation Course. Thank you very much
![Snag_1a72cbe9](https://user-images.githubusercontent.com/38166055/153783033-24646dcd-a04b-48dd-a135-ff2dc83909cd.png)
![Snag_1a72df04](https://user-images.githubusercontent.com/38166055/153783047-5b4d92b8-9e91-4dfe-8e49-4e63d5684598.png)
!

**Comment by gauravesh** [comment]
> 

 use "ubuntu-latest" instead of specifying the image
